run listeners from RF report file
reportportal/agent-Python-RobotFramework pull request #74
Opened 2020-10-21 01:59 UTC by egibbm

We have built a tool by extending your agent to allow posting results to reportportal using RF output.xml.

From the command's doc:
```
This tool replays a Robot Framework test session using the output XML file
with ReportPortal's listener agent injected without actually doing the test.
This will allow all the test results to be sent to ReportPortal, after the
test is run. By doing this, we will not disturb the timing when the test is
run. It also has the benefit of using the test result generated after running
multiple parallel robot testing (eg. by using pabot).
```

This will help solve similar issue as  #65.

Let me know if you're interested in merging this to yours. I'll be glad to help.

2020-10-21 08:04 UTC, iivanou requested changes
Apart from the other comments. What are the major benefits of this implementation comparing to the built-in import functionality of the ReportPortal UI?

![image](https://user-images.githubusercontent.com/8349078/96691077-23fc8400-138d-11eb-98eb-6585d51b6b79.png)

2020-10-21 08:04 UTC, iivanou commented on setup.py
> +__version__ = '5.0.3-postreport'
Change version to 5.0.4

2020-10-21 08:04 UTC, iivanou commented on robotframework_reportportal/variables.py
> +        try:
return _variables.get(name, default) without try/except block.

2020-10-21 08:25 UTC, egibbm commented
> Apart from the other comments. What are the major benefits of this implementation comparing to the built-in import functionality of the ReportPortal UI?
> 
> ![image](https://user-images.githubusercontent.com/8349078/96691077-23fc8400-138d-11eb-98eb-6585d51b6b79.png)

the import interface only capable of handling xunit format, which is inadequate / do not provide as complete information as the one provided by listeners. It does not record keywords, so we miss the ability to trace issues/flakiness from the reportportal UI.

2020-10-21 09:40 UTC, egibbm commented
btw do we still need to support python2? The check is false positive.
![image](https://user-images.githubusercontent.com/39547572/96702531-098dcf00-13bc-11eb-925e-d951b9478622.png)

2020-10-22 08:01 UTC, iivanou commented
> btw do we still need to support python2? The check is false positive.
> ![image](https://user-images.githubusercontent.com/39547572/96702531-098dcf00-13bc-11eb-925e-d951b9478622.png)

Unfortunately, there are loads of agent consumers who are still running Python 2. If you wanna add type hints into the project, you can create *.pyi files.

2020-10-22 08:07 UTC, iivanou commented on README.md
> +The latest stable version of library can be installed directly from github:
The previous message was correct.

2020-10-26 11:34 UTC, iivanou approved these changes

2020-10-26 11:35 UTC, merged